version: '3'
services:
  prestamo_service:
    build: "Prestamo-Service/."
    ports:
      - "7076:8080"
    networks: 
      - "service-compose-net"
networks:
  service-compose-net:
    driver: bridge